### ISSUE TITLE
Please allow the user to change the color and thickness of the edges

### ISSUE THREAD

**Issue by raindropsfromsky** [rawgraphs/rawgraphs-charts#100]
**In which part of the interface would this feature applies?**

[ ] 1. Load your data
[ ] 2. Choose a chart
[ ] 3. Mapping
[x] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**
After composing the diagram, we export the image and then present it to an audience.
This may be done by inserting the image in a doc or a ppt file.
These two cases are distinct from each other: 
- In a document, people hold the document close, so all features are visible clearly
- In a presentation, some features have to be magnified, to make them visible.

By default, the edges are very thin and gray in color. 
They are very difficult to see in a presentation.

**Describe the solution you'd like**
It is best to let the user customize the edges (color+thickness of the line), so that he can optimize them for the final use.

In fact, it should be possible to change the color and thickness of the edges for each level separately.
Thus the edges at the top level can be thicker and bolder as compared to the edges used for the next level.
We can also use the edge color to convey specific meaning.

**Comment by mikima** [comment]
hi @raindropsfromsky in which chart would you like to see this feature?

**Comment by raindropsfromsky** [comment]
Well, practically all graphs have this need, depending upon the original
size of image.
Most of the times, the image has to be scaled to full page after inserting
it in the ppt.

Many a times, such images have good nodes, but almost invisible edges.
For example, in the linear dendrogram, the edges are pale gray, with a very
thin line.
Such edges are almost invisible against a white background.

In general, the user should be able to change the color and thickness of
the edges in all charts, as it is a matter of graphic design.
(All Dataviz charts must look good out of the box, so that we don't have to
edit the output image much.)

Regards
Narayan

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mikima** [comment]
Hi @raindropsfromsky, in RAWGraphs we want to focus on features that cannot be done in other softwares.
The Microsoft suite allows you to modify the thickness of strokes:

https://user-images.githubusercontent.com/907536/135646526-2c8127ff-0796-44b5-8b4f-8e1394e5a1eb.mp4
