### ISSUE TITLE
Please allow users to change the font attributes of the labels (size, type, color, bold) 

### ISSUE THREAD

**Issue by raindropsfromsky** [rawgraphs/rawgraphs-charts#102]
**For which chart are you making a suggestion? **

All charts. This is a common need.

**Describe your suggestion**

Currently, we cannot change the text format of the labels in any of the charts. Often the labels are too tiny, and difficult to read.
Therefore we should be able to edit its attributes (font type, size, color, bold, etc). 

This has to be done before exporting the image, because it is very difficult to edit the labels in the exported image using an image editor.

**Comment by mikima** [comment]
Hi @raindropsfromsky, in RAWGraphs we want to focus on features that cannot be done in other softwares.
Font style can be changed in any vector editor software/platform (e.g. Inkscape, Adobe Illustrator, Microsoft Powerpoint, Figma etc). Triyng to keep the software as simple as possible, we won't add this feature.
