### ISSUE TITLE
In linear dendrogram, the area of any node does not equal the sum of areas of its subnodes 

### ISSUE THREAD

**Issue by raindropsfromsky** [rawgraphs/rawgraphs-charts#104]
- Linear Dendrogram

**RAWGraphs Version**

2.0 Beta
(This version is now displayed in the top-LEFT corner!  Please correct the bug tracker instruction!)

**Web browser and version**
Brave 1.30.87 
Chromium: 94.0.4606.71 (Official Build) (64-bit)

**Operating System**
Win 10 Home, 64-bit

**Steps to reproduce this**
Create a dendrogram.
If a node is split into n subnodes, its area should be equal to the sum of all subnodes.
But this is NOT the case.
As a result, the chart does not show the true proportions of the nodes.

As in a Pie chart, or a Sunburst chart, a dendrogram also should show all nodes in true proportions.

In the attached file, please compare the area of any node with the total area of its subnodes.
No node has an area that equals the sum of areas of its subnodes.

**Project file**
[LinearDendrogramNodeAreas.zip](https://github.com/rawgraphs/rawgraphs-charts/files/7271902/LinearDendrogramNodeAreas.zip)

**Comment by mikima** [comment]
Areas are actually correct, also checking the files provided:
<img width="805" alt="Artboard 1@2x" src="https://user-images.githubusercontent.com/907536/232156923-aca4dc4d-12b1-4c38-8d0c-6d24c1b8d657.png">
