### ISSUE TITLE
Can't sort streamgraphs

### ISSUE THREAD

**Issue by giorgiouboldi** [rawgraphs/rawgraphs-charts#109]
**In which chart does the bug happen?**

- Streamgraph

**RAWGraphs Version**

I can't see the version on the front end @mikima :)

**Web browser and version**

Chrome Version 95.0.4638.69 (Official Build) (x86_64)

**Operating System**

MacOSX

**Steps to reproduce this**

I create the streamgraph but when i try to sort the streams by any value it doesn't do anything. This happen in series as well

**Project file**
[stremagraph-sorting.rawgraphs.zip](https://github.com/rawgraphs/rawgraphs-app/files/7505707/stremagraph-sorting.rawgraphs.zip)

**Comment by mikima** [comment]
that's strange, i can sort streams using the current app version:

https://user-images.githubusercontent.com/907536/140962767-76ed5b2c-3d1e-4704-a1b2-432fe3c84a6c.mp4

i confirm it's not possible to sort series however

**Comment by mikima** [comment]
Fixed, will be available from version v1.0.0-beta.27
