### ISSUE TITLE
Incorrect sizing of elements in a Voronoi Treemap

### ISSUE THREAD

**Issue by davidejmancino** [rawgraphs/rawgraphs-charts#121]
Hello,

I am trying to create a Voronoi Treemap of some population data in Italian cities but I believe Raw is not showing the data properly. Many elements are not proportional as they should, and as you can see in the example cities with values of 1-5 have roughly the same size as others sized ~50.

Here is a screenshot:

![immagine](https://user-images.githubusercontent.com/14164110/177601165-4528e854-3d7a-498f-a616-344ce9b87a98.png)

The issue arises with Raw version 2.0 in Firefox 102 and Chrome 103 on Windows 10, and from other people with different computers.

Attached is the Raw project file to reproduce the issue

[centro-test.zip](https://github.com/rawgraphs/rawgraphs-app/files/9056624/centro-test.zip)

If there's any additional info you might need please let me know.

**Comment by mikima** [comment]
Sizes are actually incorrect. That is due to the iterative approach of voronoi treemaps - it is computed several times to get as close as possible to the real values.

We should expose the `convergenceRatio` and `maxIterationCount` values: https://github.com/Kcnarf/d3-voronoi-treemap#voronoiTreemap_convergenceRatio

**Comment by davidejmancino** [comment]
Thanks for the quick answer, mikima! If you think more iterations would get the shapes closer to the actual values perhaps it could be a good idea to add an option to increase the number of iterations

**Comment by mikima** [comment]
after some testing, it seems that the `minWeightRatio` is the best property to be used. will be added in next release.
