### ISSUE TITLE
Charts' tooltip & interactivity in general

### ISSUE THREAD

**Issue by stephanoshadjipetrou** [rawgraphs/rawgraphs-charts#123]
Hi and thanks for this awesome package/library/app :p

I was wondering if there's any plans for adding tooltip & interactivity in general features to the charts?

**Comment by mikima** [comment]
Hi! not at the moment, neither in the short future. But it could be done with the current structure, therefore you could develop a version of the rawgraphs charts with interactions.

**Comment by stephanoshadjipetrou** [comment]
Thanks @mikima! Could you provide any pointers if any, where we can start on with developing these features?

**Comment by MohammedHussainAli** [comment]
By creating custom charts, we can impose Tootips and many other interactions directly with D3
