### ISSUE TITLE
Sankey Diagram tutorial chart has a bug

### ISSUE THREAD

**Issue by Samwich55** [rawgraphs/rawgraphs-charts#126]
While using the sample data for the Sankey Diagram, the chart does not properly arrange with the notes. 

it cannot replicate the chart generated from the tutorial video.

**Comment by mikima** [comment]
Thanks, we updated the chart and indeed the result is slightly different. we must update the tutorial.

**Comment by Samwich55** [comment]
Thank you for the reply.

**Comment by mikima** [comment]
updated the tutorial
