### ISSUE TITLE
Text size cannot be edited on the website

### ISSUE THREAD

**Issue by letshin** [rawgraphs/rawgraphs-charts#127]
As in the title. This makes it difficult to make the chart useable.

- Alluvial diagram
- Arc Diagram
- Bar chart
- Stacked bar chart
- Multiset bar chart
- Beeswarm plot
- Boxplot
- Bump chart
- Circle Packing
- Contour Plot
- Circular dendrogram
- Linear Dendrogram
- Hexagonal Binning
- Line chart
- Matrix plot
- Radar chart
- Sankey diagram
- Streamgraph
- Sunburst diagram
- Treemap diagram
- Violin plot

**Describe your suggestion**
A clear and concise description of your suggestion. You can upload images to illustrate it.

**Comment by mikima** [comment]
hi! while would be great to have more handling of texts, they bring lot of complexity, and at the moment we wont work on that
