### ISSUE TITLE
Duplication of some names in step 1

### ISSUE THREAD

**Issue by melissamackay** [rawgraphs/rawgraphs-charts#136]
**In which chart does the bug happen?**

- Alluvial diagram
- Sankey diagram

**RAWGraphs Version**

2.0

**Web browser and version**
Chrome Version 107.0.5304.89 (Official Build) (64-bit)

**Operating System**

Windows 10

**Steps to reproduce this**

Using a simple dataset with overall 19 universties describing the categories of courses they offer (3 different categories). I pull the university as the first step, then the next column is the number associated with the category of courses (1-3). For 15 of the universities, the name is only listed once in step 1 and the lines go to the numbers 1-3. But for 3 universities, no matter how i put the data in, the names are repeated and new lines go to the next step 1-3. 

**Project file**

**Additional context**

[For data vis.xlsx](https://github.com/rawgraphs/rawgraphs-app/files/9972918/For.data.vis.xlsx)

**Comment by mikima** [comment]
Not clear to me the issue. This is the result that i get, it seems correct to me. Can you annotate on the image what is wrong? thanks! (I also upload the project file to reproduce it: [viz.rawgraphs.zip](https://github.com/rawgraphs/rawgraphs-charts/files/11651546/viz.rawgraphs.zip)).
![viz](https://github.com/rawgraphs/rawgraphs-charts/assets/907536/bce7533f-88ac-437c-add8-5b6ef254ecba)

**Comment by melissamackay** [comment]
Hi there,

The issue is that a number of universities are repeated on the right. So University of British Columbia (#2), Brock University (#3), and Universite de Montreal (#4) are all repeated in the list rather than only having one instance as they should.

Melissa MacKay, PhD (she/her)
Postdoctoral Scholar, Population Medicine
University of Guelph
***@***.***

**Comment by mikima** [comment]
The issue is related to the dataset: some values has double spaces, or spaces at the end of the string (see the screenshot, i highlighted some of them). RAWGraphs intepret them as different values. I suggest you to check the dataset with a tool like [Open Refine](https://openrefine.org/) to trim whitespaces and check inconsistencies (e.g. capitalization, typos)

<img width="772" alt="Screenshot 2023-07-06 at 23 10 51" src="https://github.com/rawgraphs/rawgraphs-charts/assets/907536/bf978b54-2431-430f-a19a-d568ba77ae00">

**Comment by melissamackay** [comment]
Thanks Michele, the website is helpful as those differences are not visible in the Excel dataset.

Thanks, Melissa

Melissa MacKay, PhD (she/her)
Postdoctoral Scholar, Population Medicine
University of Guelph
***@***.***
