### ISSUE TITLE
Missing horizon graph from UI

### ISSUE THREAD

**Issue by PaulBouisset** [rawgraphs/rawgraphs-charts#81]
Hi there,

Small question, I saw this visualization in the gallery section [https://rawgraphs.io/gallery_project/datavizsociety-slacks-activity/](https://rawgraphs.io/gallery_project/datavizsociety-slacks-activity/) it's written that they use the "Horizon Graph" but I can't find this option in the RawGraph UI.

This type of visualization was removed or it is under another name?

PS: Sorry if I use the wrong label for the issue

**Comment by mikima** [comment]
Closed with f34edf9c4c23dc1b69b573765cbd562b5fad8e7d. It's available on the `dev` version, will be publicly available in the next release
