### ISSUE TITLE
Graphical inconsintency in bump chart when using "Streams" field

### ISSUE THREAD

**Issue by andreabenedetti** [rawgraphs/rawgraphs-charts#96]
**In which chart does the bug happen?**

- Bump chart

**Web browser and version**
Firefox 89.0.2

**Operating System**
macOS 11 Big Sur

**Steps to reproduce this**

**Project file**
https://gist.githubusercontent.com/andreabenedetti/993efe82c2cda30e12f14232903dd0d1/raw/a39f6573230d3fe33a18f1a1640fbc85816a1e92/issue-bumpchart.rawgraphs

**Additional context**
When specifying the "Streams" field the same as "Series" an unexpected curve interpolation appears at the end of each small multiple area chart: a small upright tail appears.

![viz-3](https://user-images.githubusercontent.com/9431034/123965937-3bc4e700-d9b5-11eb-9fd1-fb2d6a03012d.png)
_Expected behavior_

![viz-1](https://user-images.githubusercontent.com/9431034/123965991-48493f80-d9b5-11eb-8c64-7507670e873f.png)
_Unexpected behavior_

**Comment by mikima** [comment]
issue closed, will be visible from release v1.0.0-beta.23
