### ISSUE TITLE
'Expand' in Streamgraph doesn't fill the graph 100% vertically sometimes

### ISSUE THREAD

**Issue by sal-uva** [rawgraphs/rawgraphs-charts#99]
**In which chart does the bug happen?**

- Streamgraph

**RAWGraphs Version**
2.0

**Web browser and version**
Firefox 91.0.2 (also happens on Chrome)

**Operating System**
Windows 10

**Steps to reproduce this**
Import data -> Select "Streamgraph -> Select "Expand" for "Streams vertical alignment"

**Project file**
[streamgraph-bug.rawgraphs.txt](https://github.com/rawgraphs/rawgraphs-app/files/7122185/streamgraph-bug.rawgraphs.txt)

(I added .txt to the .rawgraphs file, else I couldn't upload, just remove it!)

**Additional context**
I'm using YYYY-MM dates, but it seems to persist with other values as well. For me it's most notable with "descending" as a sort value. If I'm correct, the graph should fill out 100% vertically, right?
(Thanks for the amazing tool!)

![afbeelding](https://user-images.githubusercontent.com/10960315/132360463-059d31db-948b-4199-b4e6-7868c298616a.png)

**Comment by mikima** [comment]
Really strange.

Some of the streams are not drawn with "expand" and that cause the white space.
For example, filtering the dataset on the letter I only two streams are shown with "expand" and "none" (see images below):

![none](https://user-images.githubusercontent.com/907536/135404990-a9740579-6ba5-4ac3-9537-455e4dff195a.jpg)
![silhouette](https://user-images.githubusercontent.com/907536/135404995-8f69ee17-69b9-4a18-9b2f-d8c9ca305e7d.jpg)
![wiggle](https://user-images.githubusercontent.com/907536/135404998-f989a312-b252-4845-9e2a-31aea8ea596a.jpg)
![expand](https://user-images.githubusercontent.com/907536/135405003-a39c3b8d-77f6-4933-b7cc-0db8873049f7.jpg)
I have to further test if it's something related to d3, to rawgraphs or to the dataset.
[streamgraph-bug-dataset-I.tsv.zip](https://github.com/rawgraphs/rawgraphs-charts/files/7257418/streamgraph-bug-dataset-I.tsv.zip)
[streamgraph-bug-dataset.tsv.zip](https://github.com/rawgraphs/rawgraphs-charts/files/7257432/streamgraph-bug-dataset.tsv.zip)

**Comment by sal-uva** [comment]
Fantastic, thank you!

**Comment by mikima** [comment]
hi @sal-uva, the issue is fixed, but it will be visible from release v1.0.0-beta.23
